source 'https://rubygems.org'
ruby '2.5.1'

gem 'sinatra'
gem 'sinatra-reloader'
gem 'thin'
gem 'faye-websocket'
gem 'rufus-scheduler'
gem 'foreman'
gem 'rest-client'
gem 'json'
gem 'sidekiq'
gem 'redis-namespace'
gem 'byebug'
gem 'jwt'
